#! /bin/sh
#
# Example panel for lemonbar

. $(dirname $0)/panel_colors

num_mon=$(bspc query -M | wc -l)

# read from stdin
while read -r line ; do
  bat_cap=$(cat /sys/class/power_supply/BAT0/capacity)
  if (( bat_cap > 10 )); then
  	color_bg=$COLOR_SYS_BG
  else
    color_bg=$COLOR_LOW_BG
  fi

	case $line in
		B*)
			# battery output
			bat="%{F$COLOR_SYS_FG}%{B$color_bg} ${line#?} %{B-}%{F-}"
			;;
		E*)
			# wifi output
			wif="%{F$COLOR_SYS_FG}%{B$color_bg} ${line#?} %{B-}%{F-}"
			;;
		S*)
			# clock output
			sys="%{F$COLOR_SYS_FG}%{B$color_bg} ${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$color_bg} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FREE_BG
								;;
							F*)
								# focused free desktop
								FG=$COLOR_FOCUSED_FREE_FG
								BG=$COLOR_FOCUSED_FREE_BG
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								BG=$COLOR_OCCUPIED_BG
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED_FG
								BG=$COLOR_FOCUSED_OCCUPIED_BG
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_URGENT_BG
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_FOCUSED_URGENT_FG
								BG=$COLOR_FOCUSED_URGENT_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[LTG]*)
						# layout, state and flags
						wm="${wm}%{F$COLOR_STATE_FG}%{B$color_bg} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	i=0
	#while [[ $i -le 1 ]]; do
	  printf "%s" "%{l}${wm}%{c}${title}%{r}${wif} // ${bat} // ${sys}"
		let i=i+1
	#done
	printf "\n"
done
