#! /bin/sh

bspc config border_width         1
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d "web" "dev" "con" "misc" "five" "six"

# bspc rule -a Chromium desktop=^2
