#! /bin/sh

bspc monitor -d "web" dev con misc five six

bspc config border_width        2
bspc config window_gap          20
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
