#! /bin/sh

bspc config border_width         1
bspc config window_gap           6

bspc config click_to_focus       true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor ^1 -d "one" "two"
bspc monitor ^2 -d "three" "four"
bspc monitor ^3 -d "five" "six"
